### ISSUE TITLE
Minecraft crashes with 1.0.2 but not with 1.0.1

### ISSUE THREAD

**Issue by maximogta** [Harleyoc1/DynamicTreesNaturesAura#1]
Minecraft crashes with v1.0.2 but not with v1.0.1 of this mod, idk why
No crash log, just starts loading and minecraft closes automaticly

hs_err_pid4768.log

# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000005c1f7990, pid=4768, tid=0x00000000000033fc
#
# JRE version: Java(TM) SE Runtime Environment (8.0_261-b12) (build 1.8.0_261-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.261-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0xc7990]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

**Comment by Harleyoc1** [comment]
It’s unlikely this is to do with this mod, or at least there’s nothing in the error that suggests it would be. Have you tried running it more than once and does it give the same error? Is there anything in the logs/latest.log or logs/debug.log? What forge version are you on? Have you tried updating/reinstalling Java?

**Comment by Harleyoc1** [comment]
Going to close this for now. If you have the problem again and the above doesn’t work then I will reopen.
