### ISSUE TITLE
Can't perform Ritual of the Forest

### ISSUE THREAD

**Issue by Rydelfox** [Harleyoc1/DynamicTreesNaturesAura#10]
When attempting to perform the Ritual of the Forest, using a vanilla sapling, as the instructions suggest, the game still places a dynamic tree, preventing the ritual

**Comment by Harleyoc1** [comment]
You need to turn off the replace vanilla sapling config option. It is not on by default so this should not be a problem. At some point in the future I plan on properly integrating with this feature (#8), but until then that is the only option.
