### ISSUE TITLE
Nature's Aura trees fails to load since main DynTree update

### ISSUE THREAD

**Issue by Seth0067** [Harleyoc1/DynamicTreesNaturesAura#9]
Hey - I'm trying to use this since the Dynamic Trees Beta18 update and with versions 1.2.3 and 1.2.2 i get the attached load error.  LMK if you need more info.

![dyntrees-aura](https://user-images.githubusercontent.com/22122348/126558268-d3446890-7d73-46d0-ba63-ec4984e1a304.PNG)

[Pasted Log](https://pastebin.com/pULbxGze)

**Comment by Harleyoc1** [comment]
Fixed by 112e272c595d8df664e6b7499cb141b63c99c489. New release `1.2.4` uploading now.

**Comment by Seth0067** [comment]
thank you!
